language: go
go:
  - "1.14.1"

services:
  - docker

git:
  depth: false

before_install:
    - wget -O /tmp/gommit https://github.com/antham/gommit/releases/download/v2.2.0/gommit_linux_386
    - chmod 777 /tmp/gommit ./.coverage.sh
    - docker pull quay.io/goswagger/swagger
    - docker run --rm -it -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger version

stages:
  - test
  - build

jobs:
  include:
  - stage: test
    name: Check commits
    script: perl .test-branch-commit-messages-in-travis.pl
  - script: cd fb/ && go test && cd ../statistics && go test
    name: Unit tests
  - script: "./.coverage.sh"
    name: Code coverage
  - script: docker run --rm -it -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger
      validate ./swagger.yml
    name: Validate swagger.yml

  - stage: build
    name: Build
    script: make

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - main
  - develop