language: go
python:
  - "1.15"

git:
  depth: false

before_install:
    - wget -O /tmp/gommit https://github.com/antham/gommit/releases/download/v2.2.0/gommit_linux_386
    - chmod 777 /tmp/gommit
    - chmod 777 ./coverage.sh
jobs:
  include:
    - name: "Check commits"
      script: perl .test-branch-commit-messages-in-travis.pl
    - name: "Unit tests"
      script: cd fb/ && go test && cd ../utils && go test
    - name: "Code coverage"
      script: ./coverage.sh
    - name: "Build"
      script: "docker-compose up -d"

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - main
  - develop
  - feature/Add_CI/CD