language: go
go:
  - "1.14.1"

services:
  - docker

git:
  depth: false

before_install:
    - wget -O /tmp/gommit https://github.com/antham/gommit/releases/download/v2.2.0/gommit_linux_386
    - chmod 777 /tmp/gommit ./.coverage.sh
    - docker pull quay.io/goswagger/swagger
    - alias docker run --rm -it -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
    - swagger version
jobs:
  include:
    - name: "Check commits"
      script: perl .test-branch-commit-messages-in-travis.pl
    - name: "Unit tests"
      script: cd fb/ && go test && cd ../utils && go test
    - name: "Code coverage"
      script: ./.coverage.sh
    - name: "Validate swagger.yml"
      script: swagger validate ./swagger.yml
    - name: "Build"
      script: "docker-compose up -d"

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - main
  - develop
  - feature/Add_CI/CD