// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Stat stat
//
// swagger:model stat
type Stat struct {

	// hit
	Hit int64 `json:"hit,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// int1
	Int1 int64 `json:"int1,omitempty"`

	// int2
	Int2 int64 `json:"int2,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// str1
	Str1 string `json:"str1,omitempty"`

	// str2
	Str2 string `json:"str2,omitempty"`
}

// Validate validates this stat
func (m *Stat) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stat) UnmarshalBinary(b []byte) error {
	var res Stat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
